providers = ["node"]

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.install]
cmd = "npm ci --prefer-offline"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start" 