providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_18", "npm"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm ci --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "bash start.sh"